import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="relative flex items-center justify-center flex-col w-full h-full mx-auto sm:px-16 px-6 min-h-[100vh] bg-gray-200 ">
          {children}
        </main>
      </body>
    </html>
  );
}
